title: estúdio hacker

site_name: estúdio hacker

# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: estúdio hacker

# Short description (goes below the title; it will also be used in the RSS feed)
description: processos de aprendizagem colaborativa em tecnologia e arte

# Your name, as you want it to appear underneath each post and in the footer
author: Estúdio Hacker

# Your email if you want it to be linked on the contact page
author_email: contato@estudiohacker.io

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://estudiohacker.io

theme: jekyll-theme-architect